using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;

namespace BIMPills.UI.Helpers
{
    /// <summary>
    /// Safe wrapper around Process.Start for opening documents generated by BIMPills.
    /// Validates the file extension against a whitelist before launching the shell so
    /// that only known document types can be opened (prevents accidental script execution).
    /// </summary>
    internal static class ProcessHelper
    {
        // Extensions that BIMPills generates and is allowed to open via the shell.
        private static readonly HashSet<string> _allowedExtensions = new HashSet<string>(
            StringComparer.OrdinalIgnoreCase)
        {
            ".xlsx", ".xls", ".csv",
            ".html", ".htm",
            ".pdf",
            ".txt"
        };

        /// <summary>
        /// Opens <paramref name="filePath"/> with its default application if the extension
        /// is in the safe whitelist. Silently ignores paths with unknown extensions.
        /// </summary>
        public static void OpenDocument(string filePath)
        {
            if (string.IsNullOrWhiteSpace(filePath)) return;

            var ext = Path.GetExtension(filePath);
            if (!_allowedExtensions.Contains(ext)) return;

            Process.Start(new ProcessStartInfo(filePath) { UseShellExecute = true });
        }

        /// <summary>
        /// Opens a URL or mailto: link. Only http/https/mailto schemes are accepted.
        /// </summary>
        public static void OpenUrl(string url)
        {
            if (string.IsNullOrWhiteSpace(url)) return;

            if (url.StartsWith("http://",  StringComparison.OrdinalIgnoreCase) ||
                url.StartsWith("https://", StringComparison.OrdinalIgnoreCase) ||
                url.StartsWith("mailto:",  StringComparison.OrdinalIgnoreCase))
            {
                Process.Start(new ProcessStartInfo(url) { UseShellExecute = true });
            }
        }
    }
}
