using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using BIMPills.Commands.ModelAudit;
using BIMPills.Core.Audit;

namespace BIMPills.UI.ExportAudit
{
    /// <summary>
    /// Exports a full audit report to a self-contained HTML file.
    /// No external dependencies — produces a styled, UTF-8 HTML document
    /// that opens correctly in any browser.
    /// </summary>
    public class HtmlReportExporter
    {
        public class HtmlExportOptions
        {
            public bool IncludeHealthScore { get; set; } = true;
            public bool IncludeWarnings { get; set; } = true;
            public bool IncludeElementsWithoutCategory { get; set; } = true;
            public bool IncludeLargestFamilies { get; set; } = true;
            public bool IncludeRecommendations { get; set; } = true;
            public bool IncludeUnplacedViews { get; set; } = true;
            public bool IncludePurgeableItems { get; set; } = true;
            public bool IncludeMethodology { get; set; } = true;

            // Header fields
            public string ReportTitle { get; set; } = "";
            public string ProductionDate { get; set; } = "";
            public string GeneratedBy { get; set; } = "";

            // Signature
            public string SignatureName { get; set; } = "";
            public string SignatureRole { get; set; } = "";
        }

        public string Export(ModelAuditResult result, HtmlExportOptions options, string outputPath)
        {
            var now = DateTime.Now;
            var sb = new StringBuilder();

            sb.AppendLine("<!DOCTYPE html>");
            sb.AppendLine("<html lang=\"es\">");
            sb.AppendLine("<head>");
            sb.AppendLine("<meta charset=\"UTF-8\">");
            sb.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
            sb.AppendLine($"<title>BIMPills \u2014 Informe de Auditor\u00EDa \u2014 {Esc(result.DocumentTitle)}</title>");
            sb.AppendLine(GetStyles());
            sb.AppendLine("</head>");
            sb.AppendLine("<body>");
            sb.AppendLine("<div class=\"container\">");

            // ── Header ──
            var reportTitle = !string.IsNullOrWhiteSpace(options.ReportTitle)
                ? options.ReportTitle
                : "Informe de Auditor\u00EDa";

            sb.AppendLine("<header>");
            sb.AppendLine("  <div class=\"brand\">BIMPills</div>");
            sb.AppendLine($"  <h1>{Esc(reportTitle)}</h1>");
            sb.AppendLine($"  <p class=\"subtitle\">Proyecto: <strong>{Esc(result.DocumentTitle)}</strong></p>");

            // Meta line with production date and generated by
            var metaParts = new List<string>();
            if (!string.IsNullOrWhiteSpace(options.ProductionDate))
                metaParts.Add($"Fecha de producci\u00F3n: {Esc(options.ProductionDate)}");
            if (!string.IsNullOrWhiteSpace(options.GeneratedBy))
                metaParts.Add($"Generado por: {Esc(options.GeneratedBy)}");
            metaParts.Add($"Elementos: {result.TotalElements:N0}");
            metaParts.Add($"Tama\u00F1o: {result.FileSizeLabel}");

            sb.AppendLine($"  <p class=\"meta\">{string.Join(" \u00B7 ", metaParts)}</p>");
            sb.AppendLine("</header>");

            // ── Health Score ──
            if (options.IncludeHealthScore)
            {
                var hs = result.HealthScore;
                var levelClass = hs.Level switch
                {
                    HealthLevel.Excelente => "excellent",
                    HealthLevel.Bueno => "good",
                    HealthLevel.Regular => "regular",
                    _ => "critical"
                };

                sb.AppendLine("<section class=\"score-section\">");
                sb.AppendLine("  <h2>Puntuaci\u00F3n de Salud</h2>");
                sb.AppendLine($"  <div class=\"score-card {levelClass}\">");
                sb.AppendLine($"    <div class=\"score-value\">{hs.TotalScore}</div>");
                sb.AppendLine($"    <div class=\"score-label\">/ 100 \u2014 {hs.LevelLabel}</div>");
                sb.AppendLine("  </div>");

                // Score breakdown
                sb.AppendLine("  <div class=\"score-grid\">");
                WriteScoreItem(sb, "Advertencias", hs.WarningsScore, 30, $"{hs.WarningsCount} detectadas");
                WriteScoreItem(sb, "Tama\u00F1o archivo", hs.FileSizeScore, 20, $"{hs.FileSizeMB:F1} MB");
                WriteScoreItem(sb, "Familia m\u00E1s pesada", hs.FamilySizeScore, 15, $"{hs.LargestFamilyMB:F2} MB");
                WriteScoreItem(sb, "Elementos", hs.ElementsScore, 10, $"{hs.TotalElements:N0}");
                WriteScoreItem(sb, "Vistas sin colocar", hs.UnplacedViewsScore, 10, $"{hs.UnplacedViewsCount}");
                WriteScoreItem(sb, "Elementos purgables", hs.PurgeableScore, 15, $"{hs.PurgeableCount}");
                sb.AppendLine("  </div>");
                sb.AppendLine("</section>");
            }

            // ── Warnings ──
            if (options.IncludeWarnings && result.Warnings.Count > 0)
            {
                sb.AppendLine("<section>");
                sb.AppendLine($"  <h2>Advertencias <span class=\"badge badge-red\">{result.Warnings.Count}</span></h2>");
                sb.AppendLine("  <table>");
                sb.AppendLine("    <thead><tr><th>Descripci\u00F3n</th><th>Severidad</th><th>Elementos</th></tr></thead>");
                sb.AppendLine("    <tbody>");
                foreach (var w in result.Warnings.OrderByDescending(w => w.ElementCount).Take(50))
                {
                    var sevClass = w.Severity.ToLower() switch
                    {
                        "alta" or "high" => "sev-high",
                        "media" or "medium" => "sev-med",
                        _ => "sev-low"
                    };
                    sb.AppendLine($"    <tr><td>{Esc(w.Description)}</td><td><span class=\"sev {sevClass}\">{Esc(w.Severity)}</span></td><td class=\"num\">{w.ElementCount}</td></tr>");
                }
                if (result.Warnings.Count > 50)
                    sb.AppendLine($"    <tr><td colspan=\"3\" class=\"more\">... y {result.Warnings.Count - 50} advertencias m\u00E1s</td></tr>");
                sb.AppendLine("    </tbody>");
                sb.AppendLine("  </table>");
                sb.AppendLine("</section>");
            }
            else if (options.IncludeWarnings)
            {
                sb.AppendLine("<section>");
                sb.AppendLine("  <h2>Advertencias</h2>");
                sb.AppendLine("  <p class=\"empty\">No se detectaron advertencias en el modelo. \u2713</p>");
                sb.AppendLine("</section>");
            }

            // ── Elements without category ──
            if (options.IncludeElementsWithoutCategory && result.OrphanElements.Count > 0)
            {
                sb.AppendLine("<section>");
                sb.AppendLine($"  <h2>Elementos sin Categor\u00EDa <span class=\"badge badge-orange\">{result.OrphanElements.Count}</span></h2>");
                sb.AppendLine("  <table>");
                sb.AppendLine("    <thead><tr><th>ID</th><th>Nombre</th><th>Categor\u00EDa</th></tr></thead>");
                sb.AppendLine("    <tbody>");
                foreach (var el in result.OrphanElements.Take(100))
                {
                    sb.AppendLine($"    <tr><td class=\"num\">{el.Id}</td><td>{Esc(el.Name)}</td><td>{Esc(el.Category ?? "\u2014")}</td></tr>");
                }
                if (result.OrphanElements.Count > 100)
                    sb.AppendLine($"    <tr><td colspan=\"3\" class=\"more\">... y {result.OrphanElements.Count - 100} elementos m\u00E1s</td></tr>");
                sb.AppendLine("    </tbody>");
                sb.AppendLine("  </table>");
                sb.AppendLine("</section>");
            }
            else if (options.IncludeElementsWithoutCategory)
            {
                sb.AppendLine("<section>");
                sb.AppendLine("  <h2>Elementos sin Categor\u00EDa</h2>");
                sb.AppendLine("  <p class=\"empty\">Todos los elementos tienen categor\u00EDa asignada. \u2713</p>");
                sb.AppendLine("</section>");
            }

            // ── Largest Families ──
            if (options.IncludeLargestFamilies && result.Families.Count > 0)
            {
                var topFamilies = result.Families
                    .OrderByDescending(f => f.SizeBytes)
                    .Take(30)
                    .ToList();

                sb.AppendLine("<section>");
                sb.AppendLine($"  <h2>Familias m\u00E1s Grandes <span class=\"badge badge-blue\">{result.Families.Count} familias</span></h2>");
                sb.AppendLine("  <table>");
                sb.AppendLine("    <thead><tr><th>Familia</th><th>Categor\u00EDa</th><th>Instancias</th><th>Tama\u00F1o</th></tr></thead>");
                sb.AppendLine("    <tbody>");
                foreach (var f in topFamilies)
                {
                    var sizeClass = f.SizeMB > 2 ? "size-danger" : f.SizeMB > 1 ? "size-warn" : "";
                    sb.AppendLine($"    <tr><td>{Esc(f.Name)}</td><td>{Esc(f.Category)}</td><td class=\"num\">{f.InstanceCount}</td><td class=\"num {sizeClass}\">{f.SizeLabel}</td></tr>");
                }
                sb.AppendLine("    </tbody>");
                sb.AppendLine("  </table>");
                sb.AppendLine("</section>");
            }

            // ── Unplaced Views ──
            if (options.IncludeUnplacedViews && result.UnplacedViews.Count > 0)
            {
                sb.AppendLine("<section>");
                sb.AppendLine($"  <h2>Vistas sin Colocar en Planos <span class=\"badge badge-orange\">{result.UnplacedViews.Count}</span></h2>");
                sb.AppendLine("  <table>");
                sb.AppendLine("    <thead><tr><th>Nombre</th><th>Tipo de Vista</th></tr></thead>");
                sb.AppendLine("    <tbody>");
                foreach (var v in result.UnplacedViews.Take(50))
                {
                    sb.AppendLine($"    <tr><td>{Esc(v.Name)}</td><td>{Esc(v.ViewType)}</td></tr>");
                }
                if (result.UnplacedViews.Count > 50)
                    sb.AppendLine($"    <tr><td colspan=\"2\" class=\"more\">... y {result.UnplacedViews.Count - 50} vistas m\u00E1s</td></tr>");
                sb.AppendLine("    </tbody>");
                sb.AppendLine("  </table>");
                sb.AppendLine("</section>");
            }

            // ── Purgeable Items ──
            if (options.IncludePurgeableItems && result.PurgeableItems.Count > 0)
            {
                sb.AppendLine("<section>");
                sb.AppendLine($"  <h2>Elementos Purgables <span class=\"badge badge-red\">{result.PurgeableItems.Count}</span></h2>");
                sb.AppendLine("  <table>");
                sb.AppendLine("    <thead><tr><th>Nombre</th><th>Categor\u00EDa</th><th>Tipo</th><th>Tama\u00F1o</th></tr></thead>");
                sb.AppendLine("    <tbody>");
                foreach (var p in result.PurgeableItems.OrderByDescending(p => p.SizeBytes).Take(50))
                {
                    sb.AppendLine($"    <tr><td>{Esc(p.Name)}</td><td>{Esc(p.Category)}</td><td>{Esc(p.ItemType)}</td><td class=\"num\">{p.SizeLabel}</td></tr>");
                }
                if (result.PurgeableItems.Count > 50)
                    sb.AppendLine($"    <tr><td colspan=\"4\" class=\"more\">... y {result.PurgeableItems.Count - 50} elementos m\u00E1s</td></tr>");
                sb.AppendLine("    </tbody>");
                sb.AppendLine("  </table>");
                sb.AppendLine("</section>");
            }

            // ── Recommendations ──
            if (options.IncludeRecommendations)
            {
                sb.AppendLine("<section class=\"recs\">");
                sb.AppendLine("  <h2>Recomendaciones</h2>");
                sb.AppendLine("  <ul>");

                var recs = BuildRecommendations(result);
                foreach (var rec in recs)
                    sb.AppendLine($"    <li>{Esc(rec)}</li>");

                if (recs.Count == 0)
                    sb.AppendLine("    <li class=\"ok\">El modelo se encuentra en buen estado. No se requieren acciones inmediatas.</li>");

                sb.AppendLine("  </ul>");
                sb.AppendLine("</section>");
            }

            // ── Methodology ──
            if (options.IncludeMethodology)
            {
                var hs = result.HealthScore;
                sb.AppendLine("<section class=\"methodology\">");
                sb.AppendLine("  <h2>Metodolog\u00EDa de Evaluaci\u00F3n</h2>");
                sb.AppendLine("  <p>La puntuaci\u00F3n de salud (0\u2013100) eval\u00FAa 6 criterios ponderados, alineados con ISO 19650, Autodesk Best Practices y BIM Forum LOD Specification.</p>");
                sb.AppendLine("  <table class=\"meth-table\">");
                sb.AppendLine("    <thead><tr><th>Criterio</th><th>Puntaje</th><th>M\u00E1ximo</th><th>Referencia</th></tr></thead>");
                sb.AppendLine("    <tbody>");
                sb.AppendLine($"    <tr><td>Advertencias</td><td class=\"num\">{hs.WarningsScore}</td><td class=\"num\">30</td><td>ISO 19650-1 \u00A711.1</td></tr>");
                sb.AppendLine($"    <tr><td>Tama\u00F1o de archivo</td><td class=\"num\">{hs.FileSizeScore}</td><td class=\"num\">20</td><td>ISO 19650-2 \u00A75.2.2</td></tr>");
                sb.AppendLine($"    <tr><td>Familia m\u00E1s pesada</td><td class=\"num\">{hs.FamilySizeScore}</td><td class=\"num\">15</td><td>BIM Forum LOD Spec</td></tr>");
                sb.AppendLine($"    <tr><td>Cantidad de elementos</td><td class=\"num\">{hs.ElementsScore}</td><td class=\"num\">10</td><td>Autodesk Best Practices</td></tr>");
                sb.AppendLine($"    <tr><td>Vistas sin colocar</td><td class=\"num\">{hs.UnplacedViewsScore}</td><td class=\"num\">10</td><td>AEC (UK) BIM Protocol v2</td></tr>");
                sb.AppendLine($"    <tr><td>Elementos purgables</td><td class=\"num\">{hs.PurgeableScore}</td><td class=\"num\">15</td><td>ISO 19650-1 \u00A78.1</td></tr>");
                sb.AppendLine("    </tbody>");
                sb.AppendLine($"    <tfoot><tr><td><strong>Total</strong></td><td class=\"num\"><strong>{hs.TotalScore}</strong></td><td class=\"num\"><strong>100</strong></td><td></td></tr></tfoot>");
                sb.AppendLine("  </table>");
                sb.AppendLine("</section>");
            }

            // ── Signature ──
            if (!string.IsNullOrWhiteSpace(options.SignatureName))
            {
                sb.AppendLine("<section class=\"signature\">");
                sb.AppendLine("  <div class=\"sig-block\">");
                sb.AppendLine("    <div class=\"sig-line\"></div>");
                sb.AppendLine($"    <div class=\"sig-name\">{Esc(options.SignatureName)}</div>");
                if (!string.IsNullOrWhiteSpace(options.SignatureRole))
                    sb.AppendLine($"    <div class=\"sig-role\">{Esc(options.SignatureRole)}</div>");
                sb.AppendLine("  </div>");
                sb.AppendLine("</section>");
            }

            // ── Footer ──
            sb.AppendLine("<footer>");
            sb.AppendLine($"  <p>Creado en <strong>BIM Pills</strong> \u2014 Herramienta BIM desarrollada por <strong>BIM-CA</strong> \u2014 <a href=\"https://bim-ca.com\">bim-ca.com</a></p>");
            sb.AppendLine("</footer>");

            sb.AppendLine("</div>"); // container
            sb.AppendLine("</body>");
            sb.AppendLine("</html>");

            File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
            return outputPath;
        }

        private static List<string> BuildRecommendations(ModelAuditResult result)
        {
            var recs = new List<string>();
            var hs = result.HealthScore;

            if (hs.WarningsCount > 100)
                recs.Add($"Resolver advertencias del modelo ({hs.WarningsCount} detectadas). Priorizar las de mayor impacto.");
            else if (hs.WarningsCount > 0)
                recs.Add($"Revisar las {hs.WarningsCount} advertencias pendientes.");

            if (result.OrphanElements.Count > 0)
                recs.Add($"Asignar categor\u00EDa a los {result.OrphanElements.Count} elementos sin clasificar.");

            if (hs.LargestFamilyMB > 2)
                recs.Add($"Optimizar la familia m\u00E1s pesada ({hs.LargestFamilyMB:F1} MB). Familias >2 MB degradan el rendimiento.");

            if (hs.UnplacedViewsCount > 15)
                recs.Add($"Eliminar o colocar en planos las {hs.UnplacedViewsCount} vistas sin usar.");

            if (hs.PurgeableCount > 30)
                recs.Add($"Purgar los {hs.PurgeableCount} elementos no utilizados para reducir el tama\u00F1o del modelo.");

            if (hs.FileSizeMB > 300)
                recs.Add($"El modelo pesa {hs.FileSizeMB:F0} MB. Considere dividirlo en v\u00EDnculos para mejorar la colaboraci\u00F3n.");

            if (hs.TotalScore < 60)
                recs.Add("Ejecutar una purga completa del modelo para mejorar el Health Score.");

            return recs;
        }

        private static void WriteScoreItem(StringBuilder sb, string label, int score, int max, string detail)
        {
            int pct = max > 0 ? (int)(score * 100.0 / max) : 0;
            var barClass = pct >= 70 ? "bar-good" : pct >= 40 ? "bar-warn" : "bar-bad";
            sb.AppendLine($"    <div class=\"score-item\">");
            sb.AppendLine($"      <div class=\"si-label\">{label}</div>");
            sb.AppendLine($"      <div class=\"si-bar\"><div class=\"si-fill {barClass}\" style=\"width:{pct}%\"></div></div>");
            sb.AppendLine($"      <div class=\"si-score\">{score}/{max}</div>");
            sb.AppendLine($"      <div class=\"si-detail\">{detail}</div>");
            sb.AppendLine($"    </div>");
        }

        private static string Esc(string text)
        {
            if (string.IsNullOrEmpty(text)) return "";
            return text
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;")
                .Replace("\"", "&quot;");
        }

        private static string GetStyles()
        {
            return @"<style>
  :root { --accent: #EF6337; --primary: #1A1A2E; --blue: #1565C0; --green: #2E7D32; --red: #D32F2F; --orange: #E65100; --bg: #F5F5F7; --card: #FFFFFF; --border: #E5E5EA; --text2: #86868B; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif; background: var(--bg); color: var(--primary); line-height: 1.5; }
  .container { max-width: 900px; margin: 0 auto; padding: 30px 20px; }

  header { text-align: center; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 3px solid var(--accent); }
  .brand { font-size: 11px; text-transform: uppercase; letter-spacing: 3px; color: var(--accent); font-weight: 700; margin-bottom: 4px; }
  h1 { font-size: 26px; font-weight: 700; color: var(--primary); margin-bottom: 6px; }
  .subtitle { font-size: 14px; color: var(--primary); }
  .meta { font-size: 12px; color: var(--text2); margin-top: 4px; }

  section { background: var(--card); border-radius: 10px; padding: 20px 24px; margin-bottom: 16px; border: 1px solid var(--border); }
  h2 { font-size: 16px; font-weight: 600; color: var(--primary); margin-bottom: 14px; display: flex; align-items: center; gap: 8px; }
  .badge { font-size: 11px; font-weight: 600; padding: 2px 10px; border-radius: 12px; }
  .badge-red { background: #FFEBEE; color: var(--red); }
  .badge-orange { background: #FFF3E0; color: var(--orange); }
  .badge-blue { background: #E3F2FD; color: var(--blue); }

  /* Score */
  .score-section { text-align: center; }
  .score-card { display: inline-block; padding: 20px 40px; border-radius: 14px; margin-bottom: 20px; }
  .score-card.excellent { background: linear-gradient(135deg, #E8F5E9, #C8E6C9); }
  .score-card.good { background: linear-gradient(135deg, #E3F2FD, #BBDEFB); }
  .score-card.regular { background: linear-gradient(135deg, #FFF3E0, #FFE0B2); }
  .score-card.critical { background: linear-gradient(135deg, #FFEBEE, #FFCDD2); }
  .score-value { font-size: 52px; font-weight: 800; line-height: 1; }
  .score-label { font-size: 14px; color: var(--text2); margin-top: 4px; }
  .score-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 10px; text-align: left; }
  .score-item { background: var(--bg); border-radius: 8px; padding: 10px 14px; }
  .si-label { font-size: 11px; font-weight: 600; color: var(--text2); text-transform: uppercase; letter-spacing: 0.5px; }
  .si-bar { height: 6px; background: #E0E0E0; border-radius: 3px; margin: 6px 0; overflow: hidden; }
  .si-fill { height: 100%; border-radius: 3px; transition: width 0.3s; }
  .bar-good { background: var(--green); }
  .bar-warn { background: var(--orange); }
  .bar-bad { background: var(--red); }
  .si-score { font-size: 14px; font-weight: 700; }
  .si-detail { font-size: 11px; color: var(--text2); }

  /* Tables */
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  thead { background: var(--bg); }
  th { text-align: left; padding: 8px 12px; font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; color: var(--text2); font-weight: 600; border-bottom: 2px solid var(--border); }
  td { padding: 7px 12px; border-bottom: 1px solid var(--border); }
  tr:hover td { background: #FAFAFA; }
  .num { text-align: right; font-variant-numeric: tabular-nums; }
  .more { text-align: center; color: var(--text2); font-style: italic; padding: 10px; }
  .empty { color: var(--green); font-weight: 500; padding: 12px 0; }

  .sev { font-size: 10px; font-weight: 600; padding: 2px 8px; border-radius: 4px; text-transform: uppercase; }
  .sev-high { background: #FFEBEE; color: var(--red); }
  .sev-med { background: #FFF3E0; color: var(--orange); }
  .sev-low { background: #E8F5E9; color: var(--green); }

  .size-danger { color: var(--red); font-weight: 600; }
  .size-warn { color: var(--orange); font-weight: 600; }

  /* Recommendations */
  .recs ul { list-style: none; }
  .recs li { padding: 8px 12px; background: var(--bg); border-radius: 6px; margin-bottom: 6px; font-size: 13px; border-left: 3px solid var(--accent); }
  .recs li.ok { border-left-color: var(--green); color: var(--green); }

  /* Methodology */
  .methodology { background: #FAFBFC; border: 1px dashed var(--border); }
  .methodology p { font-size: 12px; color: var(--text2); margin-bottom: 12px; }
  .meth-table th, .meth-table td { padding: 6px 12px; }

  /* Signature */
  .signature { background: transparent; border: none; padding: 30px 24px 10px; text-align: center; }
  .sig-block { display: inline-block; min-width: 280px; text-align: center; }
  .sig-line { border-bottom: 2px solid var(--primary); margin-bottom: 8px; height: 60px; }
  .sig-name { font-size: 14px; font-weight: 600; color: var(--primary); }
  .sig-role { font-size: 12px; color: var(--text2); margin-top: 2px; }

  footer { text-align: center; padding: 20px 0; font-size: 11px; color: var(--text2); }
  footer a { color: var(--accent); text-decoration: none; }
  footer a:hover { text-decoration: underline; }

  @media print {
    body { background: white; }
    .container { max-width: none; padding: 0; }
    section { break-inside: avoid; border: 1px solid #DDD; }
  }
  @media (max-width: 700px) {
    .score-grid { grid-template-columns: 1fr 1fr; }
  }
</style>";
        }
    }
}
